services:
  laravel.test:
    build:
      context: ./docker/8.2 x
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      WWWGROUP: '1000'
      WWWUSER: '1000'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    depends_on:
      - postgres
    networks:
      - sail

  postgres:
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - 'sail-postgres:/var/lib/postgresql/data'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-postgres:
    driver: local
