services:
  laravel.test:
    build:
      context: ./docker/8.1
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      WWWGROUP: '1000'
      WWWUSER: '1000'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail

  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
